[book]
authors = ["Leo Spratt"]
language = "en"
multilingual = false
src = "docs"
title = "Run Tool"
description = "A multi-purpose tool to aid developers in executing common tasks."

[output.html]
git-repository-url = "https://github.com/enchant97/run-tool"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/enchant97/run-tool/edit/main/{path}"
site-url = "/run-tool/"
cname = "docs.enchantedcode.co.uk"
