name: Publish App

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish-to-cratesio:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish to crates.io
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
